name: aws-oidc-test
on: [workflow_dispatch]
permissions:
  id-token: write
jobs:
  who-am-i:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS cedentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ var.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Who am I
        run: aws sts get-caller-identity